import logging
from dataclasses import dataclass

import ollama
from openai import AzureOpenAI

from config import (
    OLLAMA_MODEL,
    OLLAMA_BASE_URL,
    FOUNDRY_IQ_ENDPOINT,
    FOUNDRY_IQ_API_KEY,
    FOUNDRY_IQ_DEPLOYMENT,
    FOUNDRY_IQ_API_VERSION,
    USE_FOUNDRY,
)
from reasoning.agent_isolation import IsolationFinding
from reasoning.agent_rootcause import RootCauseFinding

logger = logging.getLogger(__name__)

DAILY_DECISION_VALUE = {
    "JPM": 4_500_000,
    "BAC": 3_200_000,
    "GS": 5_100_000,
    "MS": 4_800_000,
    "C": 3_700_000,
}

PSI_DEGRADATION_COEFFICIENTS = {
    "LOW": 0.02,
    "MEDIUM": 0.08,
    "HIGH": 0.18,
    "CRITICAL": 0.35,
}


@dataclass
class RevenueImpactFinding:
    """Holds the result of the revenue impact scoring agent.

    Attributes:
        ticker: The stock ticker symbol evaluated.
        revenue_at_risk_usd: Estimated revenue at risk in US dollars.
        degradation_coefficient: Model degradation coefficient applied.
        daily_decision_value: Configured daily decision value for this ticker.
        top_feature_severity: Severity level of the top drifted feature.
        confidence_interval: Human readable confidence interval string.
        impact_summary: Natural language summary generated by the agent.
    """

    ticker: str
    revenue_at_risk_usd: float
    degradation_coefficient: float
    daily_decision_value: float
    top_feature_severity: str
    confidence_interval: str
    impact_summary: str


def calculate_revenue_at_risk(
    ticker: str,
    top_severity: str,
    psi_score: float,
) -> tuple[float, float, str]:
    """Calculate estimated revenue at risk based on PSI score and severity.

    Args:
        ticker: The stock ticker symbol.
        top_severity: The severity level of the top drifted feature.
        psi_score: The PSI score of the top drifted feature.

    Returns:
        A tuple of revenue at risk in USD, degradation coefficient used,
        and a confidence interval string.
    """
    daily_value = DAILY_DECISION_VALUE.get(ticker, 3_000_000)
    coefficient = PSI_DEGRADATION_COEFFICIENTS.get(top_severity, 0.02)

    psi_multiplier = 1.0 + (psi_score * 0.5)
    revenue_at_risk = daily_value * coefficient * psi_multiplier

    lower_bound = revenue_at_risk * 0.75
    upper_bound = revenue_at_risk * 1.35
    confidence_interval = f"${lower_bound:,.0f} — ${upper_bound:,.0f}"

    return round(revenue_at_risk, 2), coefficient, confidence_interval


def build_impact_prompt(
    ticker: str,
    isolation_finding: IsolationFinding,
    rootcause_finding: RootCauseFinding,
    revenue_at_risk: float,
    coefficient: float,
) -> str:
    """Build the prompt for the revenue impact scoring agent.

    Args:
        ticker: The stock ticker symbol being evaluated.
        isolation_finding: The findings from the isolation agent.
        rootcause_finding: The findings from the root cause agent.
        revenue_at_risk: The calculated revenue at risk in USD.
        coefficient: The degradation coefficient applied.

    Returns:
        A formatted prompt string for the model.
    """
    return (
        f"You are a financial risk analyst preparing an executive impact summary "
        f"for a data drift incident affecting {ticker}.\n\n"
        f"Drift Details:\n"
        f"Top drifted feature: {isolation_finding.top_feature}\n"
        f"PSI score: {isolation_finding.top_psi_score:.6f}\n"
        f"Severity: {isolation_finding.severity_map.get(isolation_finding.top_feature)}\n"
        f"Deviation from baseline: "
        f"{isolation_finding.deviation_map.get(isolation_finding.top_feature, 0):+.2f}%\n\n"
        f"Root Cause:\n"
        f"{rootcause_finding.hypothesis}\n"
        f"Confidence: {rootcause_finding.confidence_score:.2f}\n\n"
        f"Financial Impact:\n"
        f"Estimated revenue at risk: ${revenue_at_risk:,.2f}\n"
        f"Model degradation coefficient applied: {coefficient:.2f}\n\n"
        f"Write a two sentence executive summary of the financial impact and "
        f"urgency of this incident. Be direct, quantitative, and actionable."
    )


def call_model(prompt: str) -> str:
    """Call the configured AI model with a prompt.

    Args:
        prompt: The prompt string to send to the model.

    Returns:
        The model response text.

    Raises:
        RuntimeError: If the model call fails.
    """
    if USE_FOUNDRY:
        client = AzureOpenAI(
            azure_endpoint=FOUNDRY_IQ_ENDPOINT,
            api_key=FOUNDRY_IQ_API_KEY,
            api_version=FOUNDRY_IQ_API_VERSION,
        )
        response = client.chat.completions.create(
            model=FOUNDRY_IQ_DEPLOYMENT,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=300,
        )
        return response.choices[0].message.content.strip()
    else:
        client = ollama.Client(host=OLLAMA_BASE_URL)
        response = client.chat(
            model=OLLAMA_MODEL,
            messages=[{"role": "user", "content": prompt}],
        )
        return response["message"]["content"].strip()


async def run_impact(
    ticker: str,
    isolation_finding: IsolationFinding,
    rootcause_finding: RootCauseFinding,
) -> RevenueImpactFinding:
    """Run the revenue impact scoring agent to estimate financial exposure.

    Args:
        ticker: The stock ticker symbol being evaluated.
        isolation_finding: The findings from the isolation agent.
        rootcause_finding: The findings from the root cause agent.

    Returns:
        A RevenueImpactFinding dataclass with revenue at risk and impact summary.

    Raises:
        RuntimeError: If the model call fails after retries.
    """
    top_severity = isolation_finding.severity_map.get(
        isolation_finding.top_feature, "LOW"
    )

    revenue_at_risk, coefficient, confidence_interval = calculate_revenue_at_risk(
        ticker=ticker,
        top_severity=top_severity,
        psi_score=isolation_finding.top_psi_score,
    )

    prompt = build_impact_prompt(
        ticker=ticker,
        isolation_finding=isolation_finding,
        rootcause_finding=rootcause_finding,
        revenue_at_risk=revenue_at_risk,
        coefficient=coefficient,
    )

    try:
        impact_summary = call_model(prompt)
    except Exception as error:
        logger.error(f"Impact agent failed for {ticker}: {error}")
        raise RuntimeError(f"Impact agent model call failed: {error}")

    daily_value = DAILY_DECISION_VALUE.get(ticker, 3_000_000)

    return RevenueImpactFinding(
        ticker=ticker,
        revenue_at_risk_usd=revenue_at_risk,
        degradation_coefficient=coefficient,
        daily_decision_value=float(daily_value),
        top_feature_severity=top_severity,
        confidence_interval=confidence_interval,
        impact_summary=impact_summary,
    )