import asyncio
import logging
from dataclasses import dataclass

import ollama
from openai import AzureOpenAI

from config import (
    OLLAMA_MODEL,
    OLLAMA_BASE_URL,
    FOUNDRY_IQ_ENDPOINT,
    FOUNDRY_IQ_API_KEY,
    FOUNDRY_IQ_DEPLOYMENT,
    FOUNDRY_IQ_API_VERSION,
    USE_FOUNDRY,
)
from detection.psi_calculator import PSIResult, Severity

logger = logging.getLogger(__name__)


@dataclass
class IsolationFinding:
    """Holds the result of the feature isolation agent.

    Attributes:
        ticker: The stock ticker symbol evaluated.
        drifted_features: List of feature names that have drifted.
        psi_scores: Dictionary mapping feature names to their PSI scores.
        severity_map: Dictionary mapping feature names to their severity levels.
        top_feature: The feature with the highest PSI score.
        top_psi_score: The PSI score of the top drifted feature.
        deviation_map: Dictionary mapping feature names to deviation percentages.
        summary: Natural language summary generated by the agent.
    """

    ticker: str
    drifted_features: list[str]
    psi_scores: dict[str, float]
    severity_map: dict[str, str]
    top_feature: str
    top_psi_score: float
    deviation_map: dict[str, float]
    summary: str


def filter_drifted_features(psi_results: list[PSIResult]) -> list[PSIResult]:
    """Filter PSI results to only those with severity above LOW.

    Args:
        psi_results: Full list of PSIResult objects from the detection layer.

    Returns:
        A filtered list of PSIResult objects where drift has been detected.
    """
    return [
        r for r in psi_results
        if r.severity in (Severity.MEDIUM, Severity.HIGH, Severity.CRITICAL)
    ]


def rank_by_severity(drifted: list[PSIResult]) -> list[PSIResult]:
    """Rank drifted features by PSI score in descending order.

    Args:
        drifted: List of PSIResult objects where drift has been detected.

    Returns:
        A sorted list with the highest PSI scores first.
    """
    return sorted(drifted, key=lambda r: r.psi_score, reverse=True)


def build_isolation_prompt(ticker: str, ranked: list[PSIResult]) -> str:
    """Build the prompt for the isolation agent.

    Args:
        ticker: The stock ticker symbol being investigated.
        ranked: Ranked list of drifted PSIResult objects.

    Returns:
        A formatted prompt string for the model.
    """
    feature_lines = "\n".join([
        f"Feature: {r.feature} | PSI: {r.psi_score:.6f} | "
        f"Severity: {r.severity.value} | Deviation: {r.deviation_pct:+.2f}%"
        for r in ranked
    ])

    return (
        f"You are a financial data drift analyst. Analyze the following drift "
        f"detection results for the stock ticker {ticker}.\n\n"
        f"Drifted features ranked by severity:\n{feature_lines}\n\n"
        f"Provide a concise two sentence summary identifying which features "
        f"are most concerning and what the deviation pattern suggests about "
        f"the underlying data quality. Be specific and technical."
    )


def call_model(prompt: str) -> str:
    """Call the configured AI model with a prompt.

    Args:
        prompt: The prompt string to send to the model.

    Returns:
        The model response text.

    Raises:
        RuntimeError: If the model call fails.
    """
    if USE_FOUNDRY:
        client = AzureOpenAI(
            azure_endpoint=FOUNDRY_IQ_ENDPOINT,
            api_key=FOUNDRY_IQ_API_KEY,
            api_version=FOUNDRY_IQ_API_VERSION,
        )
        response = client.chat.completions.create(
            model=FOUNDRY_IQ_DEPLOYMENT,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=300,
        )
        return response.choices[0].message.content.strip()
    else:
        client = ollama.Client(host=OLLAMA_BASE_URL)
        response = client.chat(
            model=OLLAMA_MODEL,
            messages=[{"role": "user", "content": prompt}],
        )
        return response["message"]["content"].strip()


async def run_isolation(
    ticker: str,
    psi_results: list[PSIResult],
) -> IsolationFinding:
    """Run the feature isolation agent to identify and rank drifted features.

    Args:
        ticker: The stock ticker symbol being investigated.
        psi_results: Full list of PSIResult objects from the detection layer.

    Returns:
        An IsolationFinding dataclass with ranked drift findings and a summary.

    Raises:
        ValueError: If no drifted features are found in the PSI results.
        RuntimeError: If the model call fails.
    """
    drifted = filter_drifted_features(psi_results)

    if not drifted:
        raise ValueError(f"No drifted features found for {ticker}")

    ranked = rank_by_severity(drifted)
    top = ranked[0]

    prompt = build_isolation_prompt(ticker, ranked)

    try:
        summary = call_model(prompt)
    except Exception as error:
        logger.error(f"Isolation agent failed for {ticker}: {error}")
        raise RuntimeError(f"Isolation agent model call failed: {error}")

    return IsolationFinding(
        ticker=ticker,
        drifted_features=[r.feature for r in ranked],
        psi_scores={r.feature: r.psi_score for r in ranked},
        severity_map={r.feature: r.severity.value for r in ranked},
        top_feature=top.feature,
        top_psi_score=top.psi_score,
        deviation_map={r.feature: r.deviation_pct for r in ranked},
        summary=summary,
    )